DROP USER bbdb CASCADE;
CREATE USER bbdb 
	IDENTIFIED BY bbdb
	QUOTA 5M ON System;
GRANT 
	CONNECT,
	CREATE TABLE,
	CREATE SESSION,
	CREATE SEQUENCE,
	CREATE VIEW,
	CREATE MATERIALIZED VIEW,
	CREATE PROCEDURE,
	CREATE TRIGGER,
	PLUSTRACE,
	UNLIMITED TABLESPACE
	TO bbdb;

CONNECT bbdb/bbdb;
@load.sql
