INSERT INTO Team VALUES ('ATL','Atlanta','Hawks','Southeast','Eastern');
INSERT INTO Team VALUES ('BKN','Brooklyn','Nets','Atlantic','Eastern');
INSERT INTO Team VALUES ('BOS','Boston','Celtics','Atlantic','Eastern');
INSERT INTO Team VALUES ('CHA','Charlotte','Hornets','Southeast','Eastern');
INSERT INTO Team VALUES ('CHI','Chicago','Bulls','Central','Eastern');
INSERT INTO Team VALUES ('CLE','Cleveland','Cavaliers','Central','Eastern');
INSERT INTO Team VALUES ('DAL','Dallas','Mavericks','Southwest','Western');
INSERT INTO Team VALUES ('DEN','Denver','Nuggets','Northwest','Western');
INSERT INTO Team VALUES ('DET','Detroit','Pistons','Central','Eastern');
INSERT INTO Team VALUES ('GSW','Golden State','Warriors','Pacific','Western');
INSERT INTO Team VALUES ('HOU','Houston','Rockets','Southwest','Western');
INSERT INTO Team VALUES ('IND','Indiana','Pacers','Central','Eastern');
INSERT INTO Team VALUES ('LAC','Los Angeles','Clippers','Pacific','Western');
INSERT INTO Team VALUES ('LAL','Los Angeles','Lakers','Pacific','Western');
INSERT INTO Team VALUES ('MEM','Memphis','Grizzlies','Southwest','Western');
INSERT INTO Team VALUES ('MIA','Miami','Heat','Southeast','Eastern');
INSERT INTO Team VALUES ('MIL','Milwaukee','Bucks','Central','Eastern');
INSERT INTO Team VALUES ('MIN','Minnesota','Timberwolves','Northwest','Western');
INSERT INTO Team VALUES ('NOP','New Orleans','Pelicans','Southwest','Western');
INSERT INTO Team VALUES ('NYK','New York','Knicks','Atlantic','Eastern');
INSERT INTO Team VALUES ('OKC','Oklahoma City','Thunder','Northwest','Western');
INSERT INTO Team VALUES ('ORL','Orlando','Magic','Southeast','Eastern');
INSERT INTO Team VALUES ('PHI','Philadelphia','76ers','Atlantic','Eastern');
INSERT INTO Team VALUES ('PHX','Phoenix','Suns','Pacific','Western');
INSERT INTO Team VALUES ('POR','Portland','Trail Blazers','Northwest','Western');
INSERT INTO Team VALUES ('SAC','Sacramento','Kings','Pacific','Western');
INSERT INTO Team VALUES ('SAS','San Antonio','Spurs','Southwest','Western');
INSERT INTO Team VALUES ('TOR','Toronto','Raptors','Atlantic','Eastern');
INSERT INTO Team VALUES ('UTA','Utah','Jazz','Northwest','Western');
INSERT INTO Team VALUES ('WAS','Washington','Wizards','Southeast','Eastern');
